### ISSUE TITLE
百度网盘链接失效了

### ISSUE THREAD

**Issue by OovessaliusoO** [hongwenjun/CodeBlocks#1]
大佬可以补一下百度网盘的链接吗?

**Comment by hongwenjun** [comment]
编译器文件  百度网盘下载，链接地址 http://pan.baidu.com/s/1dD6Qrap

经过测试，可以正常下载

**Comment by OovessaliusoO** [comment]
嗯, 好的, 谢谢. 请问能否补一下您制作的CodeBlocks 2018增强版的链接? 还是说这两个链接其实是一样的么?Code::Blocks 2018 增强版 By 蘭雅sRGB
https://yun.baidu.com/s/1osEHZZPBXh_AppKblTHD4A




------------------ 原始邮件 ------------------
发件人: "蘭雅sRGB"<notifications@github.com>; 
发送时间: 2019年8月2日(星期五) 晚上7:43
收件人: "hongwenjun/CodeBlocks"<CodeBlocks@noreply.github.com>; 
抄送: "1023925196"<1023925196@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [hongwenjun/CodeBlocks] 百度网盘链接失效了 (#1)




编译器文件  百度网盘下载，链接地址 http://pan.baidu.com/s/1dD6Qrap
 
经过测试，可以正常下载

**Comment by hongwenjun** [comment]
> 嗯, 好的, 谢谢. 请问能否补一下您制作的CodeBlocks 2018增强版的链接? 还是说这两个链接其实是一样的么?Code::Blocks 2018 增强版 By 蘭雅sRGB https://yun.baidu.com/s/1osEHZZPBXh_AppKblTHD4A
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "蘭雅sRGB"<notifications@github.com>; 发送时间: 2019年8月2日(星期五) 晚上7:43 收件人: "hongwenjun/CodeBlocks"<CodeBlocks@noreply.github.com>; 抄送: "1023925196"<1023925196@qq.com>; "Author"<author@noreply.github.com>; 主题: Re: [hongwenjun/CodeBlocks] 百度网盘链接失效了 (#1) 编译器文件 百度网盘下载，链接地址 http://pan.baidu.com/s/1dD6Qrap 经过测试，可以正常下载 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or mute the thread.
